# Generated by Django 5.1.4 on 2025-01-17 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_options_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'بخش ها'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'نظرات'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'اخبار'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='details',
            new_name='detail',
        ),
    ]
